flaskblog/posts/routes.py
import operator
import pandas as pd
import os
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import *
from flaskblog.posts.forms import *
from flaskblog.users.forms import *
from flaskblog.posts.utils import *
posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    themes = Theme.query.all()
    theme_choices = [(th.id, th.name)for th in themes]
    form.theme.choices = theme_choices
    if(current_user.acc_rights == 2):
        flash('You don''t have the rights to acces this page ', 'danger')
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user, start_date=form.date.data,
                    zoom_link=form.zoom_link.data, youtube_url=form.youtube_url.data, price=form.price.data,
                    description=form.description.data, num_posts=form.num_posts.data, theme=form.theme.data)
        db.session.add(post)
        db.session.commit()
        for i in range(1, form.num_posts.data+1):
            sceance = Sceance(title=form.title.data +
                              "-Sceance "+str(i), session_id=post.id, start_date=form.date.data, num=i, content="")
            db.session.add(sceance)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('new_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/delete_sub", methods=['GET', 'POST'])
def delete_sub():
    subform = SubForm()
    sub_id = subform.sub_id.data
    sub = Subscription.query.get(sub_id)
    post_id = sub.post_id
    mode = subform.mode.data
    if(mode == '1'):
        sub.status = 2
    elif(mode == '2'):
        db.session.delete(sub)
    else:
        sub.status = 1
    db.session.commit()
    if(sub):
        flash('L''abonnement a été modifié avec succès', 'success')
    else:
        flash('opération échouée', 'warning')

    return redirect(url_for('posts.post', post_id=post_id))


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    form = PostForm()
    add_subs_form = AddSubsForm()
    users = User.query.all()
    add_subs_form.subs.choices = [(user.id, user.username) for user in users]
    themes = Theme.query.all()
    theme_choices = [(th.id, th.name)for th in themes]
    form.theme.choices = theme_choices
    subform = SubForm()
    delete_form = DeleteImageForm()
    certif_form = CertificateForm()
    post = Post.query.get_or_404(post_id)
    subs = Subscription.query.filter_by(
        post_id=post_id).all()
    users = [(sub.status, sub.id, User.query.get(sub.user_id), sub.date_posted,
              sub.payment_method) for sub in subs]
    if(request.method == "POST"):
        if form.validate_on_submit():
            if(form.images.data):
                image_file = form.images.data
                cur_image = PostImage(url=image_file, ima_post=post.id)
                db.session.add(cur_image)
                db.session.commit()
            post.title = form.title.data
            post.content = form.content.data
            post.description = form.description.data
            post.start_date = form.date.data
            post.zoom_link = form.zoom_link.data
            post.youtube_url = form.youtube_url.data
            post.price = form.price.data
            post.num_posts = form.num_posts.data
            post.theme = form.theme.data
            if(len(post.sceances) > post.num_posts):
                for i in range(post.num_posts, len(post.sceances)):
                    db.session.delete((post.sceances)[i])
            elif(len(post.sceances) < post.num_posts):
                for i in range(len(post.sceances)+1, post.num_posts+1):
                    sceance = Sceance(title=form.title.data + "-Séance "+str(i),
                                      session_id=post.id, start_date=post.start_date, num=i, content="")
                    db.session.add(sceance)
            db.session.commit()
            flash('Your post has been updated!', 'success')
            return redirect(url_for('posts.post', post_id=post.id))
        else:
            for field, errors in form.errors.items():
                flash(((', '.join(errors))), 'danger')
            return redirect(url_for('posts.post', post_id=post.id))
    return render_template('formation.html', post_id=post_id, title=post.title, post=post, add_subs_form=add_subs_form, form=form, delete_form=delete_form, users=users, certif_form=certif_form, subform=subform)


@posts.route("/post/add_subs/<int:post_id>", methods=['GET', 'POST'])
def add_subs(post_id):
    form = AddSubsForm()
    subs = Subscription.query.filter_by(post_id=post_id).all()
    if(form.validate_on_submit):
        users = form.subs.data
        for user in users:
            test = False
            for sub in subs:
                if(str(sub.user_id) == user):
                    test = True
            if(test):
                continue
            sub = Subscription(user_id=user, post_id=post_id,
                               payment_method="Ajouté par l'admin")
            db.session.add(sub)
        flash('Les abonnés ont été ajoutés avec succés', 'success')
        db.session.commit()
    return redirect(url_for('posts.post', post_id=post_id))


@ posts.route("/subscribe/<int:post_id>")
def subscribe(post_id):
    post = Post.query.get(post_id)
    return render_template('formation_inscri.html', post=post)


@ posts.route("/theme/new", methods=['GET', 'POST'])
def theme():
    form = ThemeForm()
    update_form = ThemeForm()
    delete_form = DeleteThemeForm()
    themes = Theme.query.all()
    if(request.method == 'POST'):
        if(form.validate_on_submit):
            theme = Theme(name=form.name.data, url=form.url.data)
            db.session.add(theme)
            flash('Le thème a été ajouté avec succès', 'success')
            db.session.commit()
            return redirect(url_for('posts.theme'))
    return render_template('theme.html', form=form, themes=themes, delete_form=delete_form, update_form=update_form)


@ posts.route("/search", methods=['GET', 'POST'])
def search():
    form = CertificateForm()
    url = os.path.join(
        current_app.root_path, 'static/Tableau-pour-remplir-la-base-des-certif.xlsx')
    df = pd.concat(pd.read_excel(url, sheet_name=None), ignore_index=True)
    # print(df)
    keys = ["ref", "nom", "prenom", "post", "date", "score"]
    base_certifs = []
    for j in range(len(df["ID"])):
        base_certifs.append({"ref": "", "nom": "",
                             "prenom": "", "post": "", "date": "", "score": ""})
    for i in range(len(df.keys())):
        for j in range(len(df[df.keys()[i]])):
            base_certifs[j][keys[i]] = df[df.keys()[i]][j]

    certifs = base_certifs
    for sub in Subscription.query.filter(Subscription.Certif_ref != None).all():
        certif = {"ref": "", "nom": "", "prenom": "",
                  "post": "", "date": "", "score": ""}
        certif['ref'] = sub.Certif_ref
        user = Userinfo.query.filter_by(user_id=sub.user_id).first()
        if(user):
            certif['nom'] = user.Nom
            certif['prenom'] = user.Prenom
        certif['post'] = Post.query.get(sub.post_id).title
        certif['date'] = sub.date_certif
        certif['score'] = sub.Test_score
        certifs.append(certif)
    result = None
    if((form.validate_on_submit) and (request.method == 'POST')):
        # print(form.ref.data)
        sub = Subscription.query.filter_by(
            Certif_ref=form.ref.data).first()
        for cer in base_certifs:
            if(cer["ref"] == form.ref.data):
                result = cer
        if(sub):
            certif = {"ref": "", "nom": "", "prenom": "",
                      "post": "", "date": "", "score": ""}
            certif['ref'] = sub.Certif_ref
            user = Userinfo.query.filter_by(user_id=sub.user_id).first()
            if(user):
                certif['nom'] = user.Nom
                certif['prenom'] = user.Prenom
            certif['post'] = Post.query.get(sub.post_id).title
            certif['date'] = sub.date_certif
            certif['score'] = sub.Test_score
            result = certif
        elif(result == None):
            result = "Ce certificat n'existe pas"
    return render_template('search.html', form=form, certifs=certifs, result=result)


@ posts.route("/delete_image", methods=['GET', 'POST'])
def delete_image():
    form = DeleteImageForm()
    if(form.validate_on_submit):
        print(form.image_id.data)
        image = PostImage.query.get(form.image_id.data)
        if(image):
            db.session.delete(image)
            db.session.commit()
            post_id = image.ima_post
            flash("image successfully deleted", 'success')
        else:
            flash("image not found", 'danger')
    return redirect(url_for('posts.post', post_id=post_id))


@ posts.route("/delete_document/<int:post_id>/<int:sceance_id>", methods=['GET', 'POST'])
def delete_document(post_id, sceance_id):
    form = DeleteDocumentForm()
    if(form.validate_on_submit):
        print()
        document = Document.query.get(form.document_id.data)
        if(document):
            db.session.delete(document)
            db.session.commit()
            flash("document successfully deleted", 'success')
        else:
            flash("document not found", 'danger')
    return redirect(url_for('posts.sceance', post_id=post_id, sceance_id=sceance_id))


@ posts.route("/delete_theme", methods=['GET', 'POST'])
def delete_theme():
    form = DeleteThemeForm()

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/add_certificate_modal.html
<div
  class="modal fade"
  id="certifModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          Ajouter un ceritificat
        </h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      {% from 'macros/form.html' import render_field %}
      <form
        method="POST"
        action="{{url_for('posts.certif')}}"
        enctype="multipart/form-data"
      >
        <div class="modal-body">
          <fieldset class="form-group">
            {{ form.csrf_token() }} {{ form.cert_id() }}
            <div>
              {{ render_field(form.ref) }}{{ render_field(form.score) }}
            </div>
          </fieldset>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">
            Cancel
          </button>
          {{ form.submit(class="btn btn-primary",value="Ajouter un certificat")
          }}
        </div>
      </form>
    </div>
  </div>
</div>

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/add_document_modal.html
<div
  class="modal fade"
  id="addModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ajouter un document</h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      {% from 'macros/form.html' import render_field %}
      <form
        method="POST"
        action="{{url_for('posts.add_doc', post_id=post_id, sceance_id=sceance.num)}}"
        enctype="multipart/form-data"
      >
        <div class="modal-body">
          <fieldset class="form-group">
            {{ form.csrf_token() }}
            <div>
              {{ render_field(form.title) }}{{ render_field(form.url) }}
            </div>
          </fieldset>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">
            Cancel
          </button>
          {{ form.submit(class="btn btn-primary",value="Ajouter un document")
          }}
        </div>
      </form>
    </div>
  </div>
</div>

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/add_modal.html
<div
  class="modal fade"
  id="addModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addModalLabel">Add a new user</h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <form
        method="POST"
        action="{{ url_for('users.add_user', default_url='main.add_users' ) }}"
        enctype="multipart/form-data"
        id="add-form"
      >
        <div class="modal-body">
          {{ form.csrf_token(id="add_csrf") }} {{
          form.acc_rights(class="acc_rights") }}
          <fieldset class="form-group">
            <div class="form-group">
              {{ form.username.label(class="form-control-label",
              id="add_username") }} {% if form.username.errors %} {{
              form.username(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.username(class="form-control form-control-lg")
              }} {% endif %}
            </div>
            <div class="form-group">
              {{ form.email.label(class="form-control-label",id="add_email") }}
              {% if form.email.errors %} {{ form.email(class="form-control
              form-control-lg is-invalid",id="add_email") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.email(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{
              form.password.label(class="form-control-label",id="add_password")
              }} {% if form.password.errors %} {{
              form.password(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.password(class="form-control form-control-lg")
              }} {% endif %}
            </div>
            <div class="form-group">
              {{ form.confirm_password.label(class="form-control-label") }} {%
              if form.confirm_password.errors %} {{
              form.confirm_password(class="form-control form-control-lg
              is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.confirm_password(class="form-control
              form-control-lg") }} {% endif %}
            </div>
          </fieldset>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">
            Cancel
          </button>
          {{ form.submit(class="btn btn-primary",value="Add") }}
        </div>
      </form>
    </div>
  </div>
</div>

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/add_subs_modal.html
<div
  class="modal fade"
  id="add_users_Modal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          Ajouter un ceritificat
        </h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      {% from 'macros/form.html' import render_field %}
      <form
        method="POST"
        action="{{url_for('posts.add_subs',post_id=post_id)}}"
        enctype="multipart/form-data"
      >
        <div class="modal-body">
          <fieldset class="form-group">
            {{ form.csrf_token() }}
            <div>{{ render_field(form.subs)}}</div>
          </fieldset>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">
            Cancel
          </button>
          {{ form.submit(class="btn btn-primary",value="Ajouter les abonnés") }}
        </div>
      </form>
    </div>
  </div>
</div>

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/delete_modal.html
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete this user</h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this user ?
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">
          Cancel
        </button>
        <form
          method="POST"
          action="{{url_for('users.delete_user',default_url='main.add_users' )}}"
          enctype="multipart/form-data"
          id="delete-form"
        >
          {{ form.csrf_token(id="delete_csrf") }} {{
          form.this_user(class="this_user") }} {{ form.submit(class="btn
          btn-primary") }}
        </form>
      </div>
    </div>
  </div>
</div>

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/delete_pic_modal.html
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete this image</h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this image ?
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">
          Cancel
        </button>
        <form
          method="POST"
          action="{{url_for('posts.delete_image')}}"
          enctype="multipart/form-data"
          id="delete-form"
        >
          {{ form.csrf_token() }} {{ form.image_id() }} {{
          form.submit(class="btn btn-primary",value="Delete") }}
        </form>
      </div>
    </div>
  </div>
</div>

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/delete_theme_modal.html
<div
  class="modal fade"
  id="deleteThemeModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete this image</h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <b>Are you sure you want to delete this theme ?</b></br>
        <p>Deleting this theme will cause the deletion of all posts with same theme</p>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">
          Cancel
        </button>
        <form
          method="POST"
          action="{{url_for('posts.delete_theme')}}"
          enctype="multipart/form-data"
          id="delete-form"
        >
          {{ form.csrf_token() }} {{ form.theme_id() }} {{
          form.submit(class="btn btn-primary",value="Delete") }}
        </form>
      </div>
    </div>
  </div>
</div>

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/flashes_modal.html
<div
  class="modal fade"
  id="flashes"
  tabindex="-1"
  role="dialog"
  aria-labelledby="flashModalLabel"
  aria-hidden="false"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Status</h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="container-fluid">
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %}
          <div class="flashes" id="flashes-on">
            {% for category,message in messages %}
            <div class="alert alert-{{category}}" role="alert">
              {{ message }}
            </div>
            {% endfor %}{% endif %} {% endwith %}
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button
          class="btn btn-secondary cancel"
          type="button"
          data-dismiss="modal"
        >
          Close
        </button>
      </div>
    </div>
  </div>
</div>

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/info_modal.html
<div
  class="modal fade"
  id="infoModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          Informations de l'abonnement
        </h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <b>Nom de l'utilisateur:</b><br />
        <div id="username_info"></div>
        <b>date d'inscription:</b><br />
        <div id="date_posted"></div>
        <b>Mode de paiement:</b><br />
        <div id="payement_method"></div>
        <b>Status de l'abonnement:</b><br />
        <div id="status"></div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">
          Close
        </button>
      </div>
    </div>
  </div>
</div>

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/modify_modal.html
<div
  class="modal fade"
  id="modifyModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modify current user</h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <form
        method="POST"
        action="{{url_for('users.modify_user',default_url='main.add_users' )}}"
        enctype="multipart/form-data"
        id="update-form"
      >
        {{ form.csrf_token(id="modify_csrf") }} {{
        form.this_user(class="this_user") }}
        <div class="modal-body">
          <div class="container-fluid">
            <div class="content-section">
              <div class="media">
                <img
                  class="rounded-circle account-img col-4"
                  id="img-profile"
                  src="{{image_file}}"
                />
                <div class="media-body col-8">
                  <h2 class="account-heading" id="update-username">HI</h2>
                  <p class="text-secondary" id="update-email"></p>
                </div>
              </div>

              <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                  {{
                  form.username.label(class="form-control-label",id="modify_username")
                  }} {% if form.username.errors %} {{
                  form.username(class="form-control form-control-lg is-invalid")
                  }}
                  <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  {% else %} {{ form.username(class="form-control
                  form-control-lg") }} {% endif %}
                </div>
                <div class="form-group">
                  {{
                  form.email.label(class="form-control-label",id="modify_email")
                  }} {% if form.email.errors %} {{
                  form.email(class="form-control form-control-lg
                  is-invalid",id="modify_email") }}
                  <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  {% else %} {{ form.email(class="form-control form-control-lg")
                  }} {% endif %}
                </div>
                <div class="form-group">
                  {{
                  form.password.label(class="form-control-label",id="modify_password")
                  }} {% if form.password.errors %} {{
                  form.password(class="form-control form-control-lg is-invalid")
                  }}
                  <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  {% else %} {{ form.password(class="form-control
                  form-control-lg") }} {% endif %}
                </div>
              </fieldset>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button
            class="btn btn-secondary cancel"
            type="button"
            data-dismiss="modal"
          >
            Cancel
          </button>
          {{ form.submit(class="btn btn-primary") }}
        </div>
      </form>
    </div>
  </div>
</div>

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/subform_modal.html
<div
  class="modal fade"
  id="deletesubModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          Désactiver l'abonnement
        </h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      {% from 'macros/form.html' import render_field %}
      <form
        method="POST"
        action="{{url_for('posts.delete_sub' )}}"
        enctype="multipart/form-data"
        id="delete-form"
      >
        {{ form.csrf_token() }}
        <div class="modal-body">
          Est-ce que vous êtes sûrs de désactiver cet abonnement ? {{
          form.csrf_token() }} <b>{{ render_field(form.mode) }}</b>
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">
            Cancel
          </button>

          {{form.sub_id()}}{{ form.submit(class="btn
          btn-primary",value="Modifier") }}
        </div>
      </form>
    </div>
  </div>
</div>

flaskblog/templates/startbootstrap-sb-admin-2-gh-pages/modals/update_theme_modal.html
<div
  class="modal fade"
  id="updateThemeModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Update theme</h5>
        <button
          class="close"
          type="button"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      {% from 'macros/form.html' import render_field %}
      <form
        method="POST"
        action="{{url_for('posts.update_theme' )}}"
        enctype="multipart/form-data"
        id="update-form"
      >
        <fieldset class="form-group">
          {{ form.csrf_token() }}{{ form.theme_id(id="update_theme") }}
          <div class="modal-body">
            {{ render_field(form.name,id="update_name") }} {{
            render_field(form.url,id="update_url")}}
          </div>
        </fieldset>
        <div class="modal-footer">
          <button
            class="btn btn-secondary cancel"
            type="button"
            data-dismiss="modal"
          >
            Cancel
          </button>
          {{ form.submit(class="btn btn-primary",value="Update") }}
        </div>
      </form>
    </div>
  </div>
</div>